### ISSUE TITLE
更正项目名称

### ISSUE THREAD

**Issue by sxjeru** [YoungGT/EsayCraft#2]
麻烦把“esay”改成easy。
另外原作的网站能提供给我吗？

**Comment by YoungGT** [comment]
@sxjeru OK。。失误失误
以及原帖在[这儿](http://www.mcbbs.net/thread-199037-1-1.html)，旧版[这里](http://www.mcbbs.net/thread-169732-1-1.html)，但是鬼知道[为什么](https://github.com/Trigonometry-F/NotEnoughRecipes)上不去了

**Comment by sxjeru** [comment]
呃，国人的mod。。怪不得搜不到。
@YoungGT 谢了。
